version: "3"

services:
    db:
        build: ./db
        restart: always
        environment:
                TZ: America/Sao_Paulo
                POSTGRES_USER: "${DB_USER}"
                POSTGRES_PASSWORD: "${DB_PSW}"
                POSTGRES_DB: "${DB_NAME}"
        logging:
                driver: "json-file"
                options:
                        max-file: "5"
                        max-size: "200k"
        volumes:
                - ./data/attributes_table.csv:/app/data/attributes_table.csv:ro
                - ./data/categories_table.csv:/app/data/categories_table.csv:ro
                - ./data/images_table.csv:/app/data/images_table.csv:ro
                - ./data/segmentation_table.csv:/app/data/segmentation_table.csv:ro
                - ./db/src/create_tables.sql:/docker-entrypoint-initdb.d/01-create_tables.sql
                - ./db/src/populate.py:/app/src/populate.py
                - ./db/src/populate.sh:/docker-entrypoint-initdb.d/02-populate.sh
        ports:
                - 5431:5432

#     engine:
#         build: ./engine
#         env_file: wandb.env
#         volumes:
#                 - ./engine/src:/app/src:ro
#                 - ./engine/pretrained_models:/app/pretrained_models:rw
#                 - ./data/train.csv:/app/data/train.csv:ro
#                 - ./data/label_descriptions.json:/app/data/label_descriptions.json:ro
#                 - ./data/train:/app/data/train:ro
#                 - ./data/test:/app/data/test:ro
#         depends_on:
#                 - db
#         runtime: nvidia
#         shm_size: 20GB
#         tty: true