FROM postgres:alpine

WORKDIR /usr/src/app
# ENV PG_CRON_VERSION=1.2.0
# RUN wget -O pg_cron.tgz https://github.com/citusdata/pg_cron/archive/v$PG_CRON_VERSION.tar.gz

# RUN apk update
# RUN apk add build-base
# RUN apk add ca-certificates
# RUN apk add openssl 
# RUN apk add tar
# RUN apk add libpq
# RUN apk add clang
# RUN apk add llvm

# RUN tar xvzf pg_cron.tgz

# WORKDIR pg_cron-$PG_CRON_VERSION
# RUN sed -i.bak -e 's/-Werror//g' Makefile
# RUN sed -i.bak -e 's/-Wno-implicit-fallthrough//g' Makefile
# RUN make && make install

# WORKDIR /usr/src/app
# RUN rm -rf pg_cron.tgz && rm -rf pg_cron-*
